CREATE DATABASE TennisDB1
ON
	PRIMARY (NAME = TennisDBPrimary,    
	FILENAME ='D:\Nico\PBD\Week06\TennisDBPrimary.mdf',   
	SIZE = 10MB,
	MAXSIZE = 20MB,
	FILEGROWTH = 20% ),
	 (NAME = TennisDBSecondary,
	FILENAME = 'D:\Nico\PBD\Week06\TennisDBSecondary.ndf',
	SIZE = 5MB,
	MAXSIZE = 10MB,
	FILEGROWTH = 20%)
LOG ON
	(NAME = TennisDBLog,  
	FILENAME = 'D:\Nico\PBD\Week06\TennisDBLog.ldf',
	SIZE = 30MB,
	MAXSIZE = 50MB,
	FILEGROWTH = 20%)

	--Task 2
	sp_helpDB TennisDB1

	--excercise 2
	--Task1
	ALTER DATABASE TennisDB1
	MODIFY FILE ( NAME = 'TennisDBLog',   
	SIZE = 60MB)
GO

	--Task2
	sp_helpDB TennisDB1

	--Task3
	ALTER DATABASE TennisDB1
	MODIFY FILE ( NAME = 'TennisDBLog',
	SIZE = 30MB)
GO

	--Excercise3
	--Task1
	ALTER DATABASE TennisDB1
ADD FILE 
  ( NAME = TennisDBSecondary2,
   FILENAME ='D:\Nico\PBD\Week06\TennisDBSecondary2.ndf',
   SIZE = 15MB,
   MAXSIZE = 20MB )
GO
	--Task2
	ALTER DATABASE TennisDB1
	ADD FILEGROUP TennisGroup
	
	ALTER DATABASE TennisDB1
	ADD FILE (Name = TennisDB_1,
  FileName = 'D:\Nico\PBD\Week06\TennisDB_1.ndf',
  Size = 5MB,
  MaxSize = 10MB,
  Filegrowth = 1MB),
  (Name = TennisDB_2,
   FileName = 'D:\Nico\PBD\Week06\TennisDB_2.ndf',
   Size = 5MB,
   MaxSize = 10MB,
   Filegrowth = 1MB)
TO FILEGROUP TennisGroup 

--task3
ALTER DATABASE TennisDB1
REMOVE FILE TennisDB_2

--Exercise 4
CREATE TABLE PLAYERS
(
	PLAYERNO int NOT NULL,
	NAME char(15) NOT NULL,
	INITIALS char(3) NOT NULL,
	BIRTH_DATE date NULL,
	SEX char(1) NOT NULL,
	JOINED smallint NOT NULL,
	STREET varchar(30) NOT NULL,
	HOUSENO char(4) NULL,
	POSTCODE char(6) NULL,
	TOWN varchar(30) NOT NULL,
	PHONENO char(13) NULL,
	LEAGUENO char(4) NULL,
	PRIMARY KEY (PLAYERNO)
)

CREATE TABLE TEAMS
(
TEAMNO int NOT NULL,
PLAYERNO int NOT NULL,
DIVISION char(6) NOT NULL,
PRIMARY KEY (TEAMNO),
FOREIGN KEY (PLAYERNO)
REFERENCES PLAYERS (PLAYERNO)
)

CREATE TABLE MATHCES
(
MATCHNO int NOT NULL,
TEAMNO int NOT NULL,
PLAYERNO int NOT NULL,
WON smallint NOT NULL,
LOST smallint NOT NULL
PRIMARY KEY (MATCHNO),
FOREIGN KEY (TEAMNO)
REFERENCES TEAMS (TEAMNO),
FOREIGN KEY (PLAYERNO)
REFERENCES PLAYERS (PLAYERNO)
)

CREATE TABLE PENALTIES
(
PAYMENTNO int NOT NULL,
PLAYERNO int NOT NULL,
PAYMENT_DATE date NOT NULL,
AMOUNT decimal(7,2) NOT NULL
PRIMARY KEY (PAYMENTNO),
FOREIGN KEY (PLAYERNO)
REFERENCES PLAYERS (PLAYERNO)
)

CREATE TABLE COMMITTEE_MEMBERS
(
PLAYERNO int NOT NULL,
BEGIN_DATE date NOT NULL,
END_DATE date NULL,
POSITION char(20) NULL,
PRIMARY KEY (BEGIN_DATE),
FOREIGN KEY (PLAYERNO)
REFERENCES PLAYERS (PLAYERNO)
)

